PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/spec/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX igeo: <http://rdf.insee.fr/def/geo#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?reg (COUNT(DISTINCT ?m) AS ?nbm) (COUNT(DISTINCT ?f) AS ?nbf)
WHERE
{
    {?m igeo:nom ?reg.
    ?m foaf:gender "Masculin"}
    UNION {?f igeo:nom ?reg.
    ?f foaf:gender "Feminin"}
}
GROUP BY ?reg
