PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/spec/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX igeo: <http://rdf.insee.fr/def/geo#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <https://www.w3.org/TR/rdf-schema/#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

CONSTRUCT {
  #mapping

  #Table principale
  ?URI_Record a schema:dataset;
    ex:hasEducation ?URI_EduOrganization;
    ex:hasStudent ?URI_Student;
    ex:hasRegion ?URI_Region;
    dbo:year ?annee.
    
  #Ecole
  ?URI_EduOrganization a schema:EducationalOrganization;
    ex:effectif_ing ?EFFECTIF_ING;
    ex:effectif_dut ?EFFECTIF_DUT;
    dbo:numberOfStudents ?EFFECTIF_TOT;
    dbo:educationSystem ?secteur_de_l_etablissement;
    dbo:formationYear ?annee.

  #Etudiant
  ?URI_Student a ex:student;
    foaf:gender ?sexe_de_l_etudiant.

  #Region + liens region avec autres dataset
  ?URI_Region_CPR rdf:type vcard:region;
    igeo:subdivisionDirecte ?niveau_geo;
    igeo:codeRegion ?reg_id;
    igeo:nom ?URI_Region_CPR;
    owl:sameAs ?URI_REGION_HIPPO
}
FROM <file:data_clem.csv>
WHERE {

  #Lien URI-ressources pour les mappings
  BIND (URI(CONCAT('http://ex.org/record_id/', ?recordid)) AS ?URI_Record) .

  #Pour former une "clef primaire" je me suis permis de rajouter la date de rentrée dans l'uri.
  BIND (URI(CONCAT((CONCAT((CONCAT('http://ex.org/ecole/', ?rgp_formations_ou_etablissements)),'_')),?rentree)) AS ?URI_EduOrganization) .

  BIND (URI(CONCAT('http://ex.org/student/', ?sexe_de_l_etudiant)) AS ?URI_Student) .

  BIND (URI(CONCAT('http://ex.org/region/', ?reg_id)) AS ?URI_Region) .


    #Lien URI-ressources pour les liens avec d'autres dataset
  BIND ((STRAFTER(?geo_id, "R")) AS ?codereg)
  BIND (URI(CONCAT("http://ex.org/nous/codeRegion/", ?codereg)) AS ?URI_Code_Region_NOUS)  
  BIND (URI(CONCAT("http://ex.org/budget/codeRegion/", ?codereg)) AS ?URI_Code_Region_LOIC)  
  BIND (URI(CONCAT("http://ex.org/fr-esr-rd-moyens-entreprises-intensite/codeRegion/", ?codereg)) AS ?URI_Code_Region_IVAN)

  #typage de certains attributs
  BIND (xsd:integer(?effectif_ing) AS ?EFFECTIF_ING).
  BIND (xsd:integer(?effectif_dut) AS ?EFFECTIF_DUT).
  BIND (xsd:integer(?effectif) AS ?EFFECTIF_TOT).
  BIND (xsd:gYear(?rentree) AS ?annee)

}
